source 'https://rubygems.org'

# git_source(:github) { |repo| 'https://github.com/#{repo}' }

# Specify your gem's dependencies in times.gemspec
gemspec

gem 'rack-test'
gem 'sinatra', '~> 2.0.1'
gem 'thin'
